stages:
  - move
  - build
  

build:
  stage: build
  script:
    - echo "Building the application on SSH server..."
    - hostname
    - pwd
    - ssh wifi-proxy  "mkdir -p  /home/DevOps/application/wifi-prod/ && cd /home/DevOps/application/wifi-prod/ && chmod +x ./gradlew && ./gradlew clean && ./gradlew build -x test"

    - echo "Source code built on remote server"
  only:
    - main

move:
  stage: move
  script:
    - echo "Copying  from remote server to GitLab CI/CD..."
    - hostname
    - pwd


    - ssh wifi-proxy "rm -rf /home/DevOps/application/wifi-prod/*"

    - scp -o StrictHostKeyChecking=no   -r ./*  wifi-proxy:/home/DevOps/application/wifi-prod/


    - echo "Artifacts uploaded to GitLab CI/CD."
  only:
    - main
