stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building the Spring Boot application on the SSH server..."
    - ssh wifi-proxy "mkdir -p /home/DevOps/application/wifi-dev/ && cd /home/DevOps/application/wifi-dev/ && chmod +x ./gradlew && ./gradlew clean build -x test"
    - echo "Build completed on remote server."
  only:
    - dev

deploy:
  stage: deploy
  script:
    - echo "Deploying JAR file to multiple directories on the remote server..."

    # Fetch JAR path from the build
    - ssh wifi-proxy "mkdir -p /home/DevOps/application/wifi-dev-node2 /home/DevOps/application/wifi-dev-node3"
    - JAR_FILE=$(ssh wifi-proxy "find /home/DevOps/application/wifi-dev/build/libs -name '*.jar' | head -n 1")

    - echo "JAR file found: $JAR_FILE"

    # Copy the JAR to target directories
    - ssh wifi-proxy "cp $JAR_FILE /home/DevOps/application/wifi-dev/"
    - ssh wifi-proxy "cp $JAR_FILE /home/DevOps/application/wifi-dev-node2/"
    - ssh wifi-proxy "cp $JAR_FILE /home/DevOps/application/wifi-dev-node3/"

    - echo "Deployment completed successfully."
  only:
    - dev
