spring.application.name=wifi-portal
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/wifi_portal
spring.datasource.username=wifi
spring.datasource.password=qwer1234@1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=DEBUG
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
portalBaseUrl=https://api.sasakonnect.net
portalUserName=\$2a\$10\$LaAh5xhco
portalUserPassword=Z0hKJx5RvyleG4HpvD7
devId=3Y+zGsa2OGIDvMoKBwBshYJMI4JKRzE/qgt0+NWDl4KCs07MZ/5iuNPdzOmLouWGhbrTj5JyGUtR5Tj8RK+jKQ==
subsDevId=wpcyx5b3UgYXJlIGRvaW5nIGl0IHdyb25nLmFzayBtZSB3aHk=
server.servlet.context-path=/konnect-wifi
JWT_SECRET=e9a4dbdc407883810efe0641cd196ea098475bd7bf96b8a19cbc8e99e9e75510443e3885c6b1ad51bbf4e8118535ac9848626f750002799c1bcded9607253d4131bc23d7cfb5233e51283146d13a404a9dd3b4227ea35457746bb9b4a958db3875a32885f3f71aef0182272f154c7568f22b6a3cc3b8a4a6a8ae78b5cbd137098b6bdc560361973a11e1c5f3373f115d64a37d375eb0e0d33c277261ce02db64befa3dd0e257352700be8485548b75c4f087a548f99792ed06717f41a45f23fa1152ea930cf26efc5b4f21678b8c4eee19077217cc9e2480bc329c397d70641f5b1eef4ecc0946a23854a9ad62a6559f93c568a6b790b913eb06d64c6b3c7fc4
#consumerKey=YpKHGJX2fJ9ZADA8neI7YE6qNlge9czY6x05w1ZLxAYzHQkZ
#consumerSecret=ZWFUAPWPIljnwHyjIEcI0KnrELhIjjHo0f43GZttKNM1uGECa0XdxJ7cBeouyEMZ
consumerKey=cWYIi6VMkuqOyrVaRnnAJZ4Ywwq7kFuCbm1Act7QR6SsH0jA
consumerSecret=uHESOeGt8rdZZZX0uAeJqOrBxrGuXFK1yiRGmzrYsjf1B3jNrAdQOPbQAIbP5Sqa
shortCode=5467224
mpesaCallBackUrl=https://mfood.sasakonnect.net/konnect-wifi/payment/callBack
consumerPassKey=93cbf8942bf80a1165dda3dd11377f80c7f810b1371e0fb5cde3b6cc20b50829
mpesa.api.url= https://api.safaricom.co.ke

#Rabbit Mqhttps://ab85-105-29-165-234.ngrok-free.app
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=ahdev
spring.rabbitmq.password=qwer
spring.rabbitmq.virtual-host=/

